const dataBase = require('./config')
const initDB = {
    async init() {
        const db = await dataBase();
        await db.exec(`CREATE TABLE notes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            body TEXT NOT NULL
            )`);
            await db.exec(`
            INSERT INTO notes(title,body)
            VALUES(
                'Random text 1',
                'Tristique luctus turpis porttitor libero dolor pulvinar sociosqu duis, non hendrerit tincidunt nunc elementum fames sapien, ultricies justo felis malesuada cubilia eleifend luctus. etiam arcu lobortis metus nunc imperdiet feugiat inceptos, mi curabitur platea eget erat pretium consequat morbi, netus vehicula ipsum aptent taciti pharetra. donec urna lobortis mauris rhoncus maecenas hac, donec risus pretium fusce luctus nibh porttitor, nisi quisque ac mauris sagittis. scelerisque rutrum luctus ut ullamcorper diam neque torquent turpis potenti, fames mauris faucibus elit vitae nullam nunc est curabitur, nisl et lobortis nostra augue mollis luctus egestas. 

                Habitant himenaeos phasellus tempus cras porta id ligula quam lacus blandit sociosqu, vel justo ultrices tempor lorem platea at donec magna mollis lacus vel, etiam placerat imperdiet lectus consectetur ut dictumst posuere et ultricies. dictumst felis enim velit leo ultricies per nec lacus mi, justo gravida purus primis cras torquent sodales faucibus neque, pellentesque mi dictumst fusce vehicula neque dapibus nunc. netus mi lectus velit torquent vestibulum mauris hendrerit ullamcorper mauris ante, quisque purus lacinia leo dui malesuada nam euismod facilisis, quisque mollis nibh aptent fames praesent pretium justo donec. 
            
                Ornare ullamcorper id adipiscing dapibus varius sit ut etiam conubia vitae sit, semper est suscipit malesuada nunc primis justo posuere morbi pulvinar in donec, pretium duis aptent ipsum himenaeos potenti integer lobortis fusce mollis. rhoncus et libero ultrices hac ante pellentesque blandit dolor, quisque ipsum molestie interdum integer platea convallis, laoreet elit pharetra est eu pharetra vehicula. lorem urna elementum dictum viverra sagittis primis morbi mauris et ut arcu aliquam, quisque vivamus elit vehicula venenatis lectus curabitur sapien eros vestibulum justo, tincidunt dolor accumsan fermentum augue platea id sodales habitasse leo iaculis. 
            
                Magna at lacinia dui consequat ad enim sit, consequat sit nostra et nostra ligula pulvinar, iaculis taciti augue netus per taciti. turpis curabitur lectus etiam, hac sem. '
            )
            `);
            await db.exec(`
            INSERT INTO notes(title,body)
            VALUES(
                'Random text 2',
                'Suscipit tortor curae duis lobortis primis lacus arcu potenti, hendrerit non conubia aenean duis tristique tortor tellus, dictum risus primis ultrices id tristique interdum. amet lacus enim at varius augue potenti mi nam sagittis orci neque felis litora adipiscing felis, aliquam blandit elementum lacinia ad dictumst sagittis diam leo pharetra proin scelerisque odio ultricies. per fringilla lorem et curae tellus ornare risus tellus mattis, magna libero et aenean ligula nisi ut massa at, sollicitudin senectus nisl donec neque maecenas vulputate quis. litora class ornare laoreet turpis lacus mattis vestibulum sem pulvinar cubilia, quam integer malesuada sociosqu neque vestibulum dui primis. '
                )
            `);
            await db.exec(`
            INSERT INTO notes(title,body)
            VALUES(
                'Random text 3',
                'Eros in nunc fermentum amet adipiscing magna nec, quisque sagittis gravida suscipit a integer platea, etiam curabitur suspendisse vehicula nisl nisi. adipiscing ligula habitasse litora pellentesque accumsan elementum curae taciti aliquet, aenean ad commodo at orci massa id fusce, molestie egestas donec tortor ligula placerat cursus aenean. ultricies nostra aptent cursus rhoncus nunc convallis dolor quisque leo fringilla, mi quisque molestie accumsan lectus tortor morbi eleifend fames, aliquam varius elementum pellentesque lacus nisi viverra interdum cras. at taciti velit litora cursus interdum nec magna blandit nam curae non ad mauris, cras tortor aliquet eu aliquam posuere elementum suscipit arcu dictumst curabitur. 

                Fames amet molestie sem libero duis donec eleifend dictum curae eros ipsum cubilia vestibulum, egestas placerat sociosqu dictumst auctor lacus cubilia aenean hac tortor iaculis. quis netus auctor elit pellentesque sapien aenean vestibulum aenean turpis, ut mattis justo hac sit gravida viverra venenatis velit, cursus sollicitudin primis tortor aenean nisl dapibus ullamcorper. netus eleifend erat quisque accumsan himenaeos duis tempor, mollis tempus feugiat suscipit eget sapien curabitur, sociosqu hac elementum scelerisque pretium dictumst. mollis consectetur eros pellentesque ultricies vestibulum maecenas sit integer, nibh diam eros dapibus ante nam. commodo tempor ut conubia eros convallis aenean massa donec iaculis id, congue donec curabitur nibh proin velit tempus praesent primis, hac sodales tempus fames eu justo praesent hendrerit molestie. 
            
                Ligula id lacinia mauris a viverra nulla per malesuada sollicitudin est interdum, torquent sodales pellentesque platea tristique venenatis tempor maecenas aenean conubia, mi potenti rutrum sem netus odio class accumsan sed metus. euismod ultricies est aliquet odio vulputate maecenas lobortis ultricies ipsum nullam venenatis, dictumst quis mauris vehicula mollis quisque integer leo in. morbi odio aliquam aptent semper litora sit fames lacus vehicula blandit, donec ac ipsum litora fames cursus magna adipiscing aenean, quisque aenean libero cras rutrum class sagittis tortor non. '
                )
            `);
            await db.exec(`
            INSERT INTO notes(title,body)
            VALUES(
                'Random text 4',
                'Nisi pellentesque tincidunt fames curae dui faucibus luctus, platea quam euismod varius tellus quis conubia, lectus quam duis curabitur suspendisse mollis. cubilia eros vestibulum urna augue donec fringilla sagittis nostra luctus aenean viverra, lobortis velit mollis consequat habitant vitae non porta dictum lectus. interdum eu fringilla iaculis dapibus commodo sapien nibh senectus sem mauris, erat id nisl fames augue odio lorem ante mauris diam, nulla est rutrum torquent faucibus metus inceptos mauris mi. pellentesque lacinia tellus nisi erat fringilla porta aliquam curae quis, accumsan taciti porta iaculis mauris habitant dictum aenean, placerat vestibulum fermentum nullam at urna dictumst ad. 

                A feugiat fusce rutrum tellus porttitor lorem, dictumst dapibus luctus semper etiam, litora phasellus tempus aliquam rutrum. class donec et sit eleifend egestas urna cubilia, et curabitur sed non platea ultricies eu, tincidunt nisi mi dolor est libero. gravida pulvinar torquent cras fusce bibendum maecenas, ullamcorper fusce nunc eu arcu, fermentum accumsan quam odio tellus. tortor scelerisque nec consectetur at aenean ante elementum cursus, netus proin varius pulvinar ante sed scelerisque, risus ante dui posuere a tellus feugiat. tempus potenti ipsum taciti leo ligula adipiscing gravida mollis, fringilla risus tincidunt est etiam placerat torquent. 
            
                Eget placerat duis suscipit aliquam libero condimentum class etiam, maecenas tincidunt sed condimentum dapibus blandit ipsum taciti, a cras senectus sem aenean dapibus himenaeos. fringilla conubia volutpat semper suscipit sagittis sollicitudin tincidunt, eleifend tellus a iaculis enim urna, faucibus praesent volutpat odio nam taciti. risus ac tristique in scelerisque tincidunt consectetur porttitor dui consequat, justo interdum gravida eu gravida semper taciti maecenas platea, imperdiet hendrerit arcu scelerisque eu sagittis tincidunt mattis. ante rhoncus suspendisse tristique suspendisse aenean class tristique, suscipit sollicitudin tortor etiam adipiscing praesent ornare interdum, suscipit auctor augue varius praesent facilisis. 
            
                Imperdiet bibendum aenean fermentum praesent nunc placerat curabitur primis, ipsum faucibus mauris laoreet conubia taciti eu himenaeos scelerisque, vulputate cubilia commodo fusce mollis pharetra vivamus. ad duis aliquet laoreet lacinia semper nisl ad quisque quis accumsan urna aenean ac nullam, platea habitant nostra ante suspendisse porttitor maecenas lorem pharetra torquent rhoncus libero. vestibulum nisl mi quam rutrum justo tellus laoreet, accumsan lobortis praesent massa sit dapibus. molestie augue aenean ligula cursus pulvinar ante fames cubilia aliquam, aptent phasellus vehicula himenaeos mattis imperdiet donec eget, himenaeos lorem senectus risus hac at ut senectus. 
            
                Congue cursus mi porta arcu magna quisque vel tempus platea nam, posuere per neque pretium dictumst aenean arcu sociosqu. vestibulum viverra massa eros ut tempor augue ut vestibulum imperdiet, quisque condimentum iaculis torquent massa dapibus viverra conubia iaculis per, gravida feugiat elementum cursus est donec dui fusce. tellus fusce adipiscing sem suspendisse donec curabitur, eu vivamus imperdiet tellus lobortis eget, blandit vivamus nostra torquent lacinia. mollis fusce litora suscipit bibendum tortor eleifend maecenas ut magna, mollis fringilla sed arcu consectetur non nisi nec etiam, ipsum quisque vestibulum iaculis sodales ligula tempor conubia. 
            
                Blandit imperdiet auctor id magna orci est sapien libero dapibus eleifend, augue consequat ornare venenatis nisi nibh phasellus sit dictumst vulputate enim, rhoncus pellentesque cras primis justo egestas aenean molestie pharetra. habitant dictumst torquent vitae pretium lectus hac justo odio suscipit, nec consequat hendrerit pellentesque dui mi habitasse aenean sociosqu aliquam, elit est congue tincidunt sem quam ad sed. posuere consectetur curabitur luctus bibendum cursus taciti lacinia libero adipiscing quisque vehicula enim, eu tellus curae cubilia tellus sociosqu egestas pretium massa nec lacinia ante nullam, iaculis at ut accumsan ante malesuada ligula dui class amet metus. 
            
                Venenatis vehicula vulputate ullamcorper auctor class rutrum, donec sit suspendisse ullamcorper cras aenean, ut quam hendrerit mauris scelerisque. arcu diam sem elit vehicula eget cras elit quam, justo sociosqu at himenaeos quisque elementum fames. proin fringilla imperdiet facilisis pulvinar congue donec quam, volutpat vitae pulvinar sodales tortor lectus, quisque semper tempor convallis ad ipsum. dictumst hendrerit laoreet porta non proin enim a taciti, bibendum donec suspendisse malesuada tristique et senectus dapibus a, tempus sed suspendisse consequat nulla eu justo. ultrices conubia fusce maecenas hac lobortis, faucibus adipiscing etiam vivamus, scelerisque ut aenean ultricies. 
            
                Gravida elit curabitur curae nisl ut viverra fusce suspendisse, enim venenatis sociosqu himenaeos aliquam hac malesuada, habitasse nullam vitae consectetur turpis primis aenean. ornare per lectus feugiat varius pulvinar praesent etiam ad duis est nostra himenaeos, tellus aenean at eleifend etiam tincidunt at massa varius eu enim, maecenas pellentesque hac felis rhoncus sodales risus taciti tempor conubia fusce. suspendisse donec cursus lacinia aenean vel nunc turpis cras purus, nunc velit nam in metus sociosqu accumsan. lacus mollis bibendum ligula dictum magna class per volutpat dictum, quisque dictumst habitant at ullamcorper quis urna ante enim, pharetra auctor volutpat venenatis elementum amet venenatis cras. 
            
                Himenaeos suspendisse ullamcorper gravida iaculis enim netus feugiat, tristique mi viverra tristique gravida turpis id ipsum, auctor donec primis iaculis praesent non. aliquam semper lobortis inceptos luctus lobortis turpis mollis placerat, molestie pellentesque arcu proin tellus id eget, himenaeos pretium turpis ad taciti imperdiet libero. morbi consectetur litora aliquam vulputate orci etiam eu lobortis donec accumsan enim aenean tellus donec, sapien eros nec congue auctor suspendisse odio ullamcorper quis mollis justo velit fames. rutrum donec netus himenaeos pharetra tincidunt dictumst hac, donec euismod condimentum turpis augue posuere, egestas netus lacus eleifend senectus litora. 
            
                A elementum laoreet auctor aenean porta magna quam a enim hac, quisque tincidunt auctor egestas praesent molestie litora duis scelerisque, maecenas tempor ac feugiat turpis maecenas luctus integer condimentum. enim odio metus donec adipiscing donec duis aenean pellentesque mollis, arcu sed curae cubilia aliquam tempor rutrum senectus lacinia, ligula dapibus sollicitudin mollis euismod non lacus scelerisque. malesuada eu dui aliquet congue curabitur cursus posuere mattis quisque id varius porta odio velit nulla, vel porta fringilla curabitur semper erat rutrum consectetur auctor class ultrices purus aenean inceptos. fermentum quisque lacinia duis sodales consequat per fringilla senectus mollis, per amet gravida nunc bibendum ullamcorper fringilla rutrum, viverra ut cras sapien at ad bibendum nisi. 
            
                Accumsan fringilla porttitor ornare augue vivamus dapibus, gravida sed ultricies posuere habitant sollicitudin, aliquam ac molestie sollicitudin potenti. condimentum primis viverra ut aliquam tempus, fusce etiam tincidunt maecenas sagittis magna, justo dolor nullam aenean. 
                
                Eros in nunc fermentum amet adipiscing magna nec, quisque sagittis gravida suscipit a integer platea, etiam curabitur suspendisse vehicula nisl nisi. adipiscing ligula habitasse litora pellentesque accumsan elementum curae taciti aliquet, aenean ad commodo at orci massa id fusce, molestie egestas donec tortor ligula placerat cursus aenean. ultricies nostra aptent cursus rhoncus nunc convallis dolor quisque leo fringilla, mi quisque molestie accumsan lectus tortor morbi eleifend fames, aliquam varius elementum pellentesque lacus nisi viverra interdum cras. at taciti velit litora cursus interdum nec magna blandit nam curae non ad mauris, cras tortor aliquet eu aliquam posuere elementum suscipit arcu dictumst curabitur. 

                Fames amet molestie sem libero duis donec eleifend dictum curae eros ipsum cubilia vestibulum, egestas placerat sociosqu dictumst auctor lacus cubilia aenean hac tortor iaculis. quis netus auctor elit pellentesque sapien aenean vestibulum aenean turpis, ut mattis justo hac sit gravida viverra venenatis velit, cursus sollicitudin primis tortor aenean nisl dapibus ullamcorper. netus eleifend erat quisque accumsan himenaeos duis tempor, mollis tempus feugiat suscipit eget sapien curabitur, sociosqu hac elementum scelerisque pretium dictumst. mollis consectetur eros pellentesque ultricies vestibulum maecenas sit integer, nibh diam eros dapibus ante nam. commodo tempor ut conubia eros convallis aenean massa donec iaculis id, congue donec curabitur nibh proin velit tempus praesent primis, hac sodales tempus fames eu justo praesent hendrerit molestie. 
            
                Ligula id lacinia mauris a viverra nulla per malesuada sollicitudin est interdum, torquent sodales pellentesque platea tristique venenatis tempor maecenas aenean conubia, mi potenti rutrum sem netus odio class accumsan sed metus. euismod ultricies est aliquet odio vulputate maecenas lobortis ultricies ipsum nullam venenatis, dictumst quis mauris vehicula mollis quisque integer leo in. morbi odio aliquam aptent semper litora sit fames lacus vehicula blandit, donec ac ipsum litora fames cursus magna adipiscing aenean, quisque aenean libero cras rutrum class sagittis tortor non.' 
                )
            `);
        await db.close();
    }
}
initDB.init();
